In [95]:
import os
import kagglehub
import pandas as pd

In [96]:
path = kagglehub.dataset_download("rishikeshkonapure/zomato")
file_path = os.path.join(path, "zomato.csv")
df = pd.read_csv(file_path)

In [97]:
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [98]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [99]:
columns_to_keep = ['name', 'online_order', 'book_table', 'rate', 'dish_liked', 'approx_cost(for two people)']
columns_to_drop = ['url', 'address', 'votes',
       'phone', 'location', 'rest_type', 'cuisines', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)']

In [100]:
df.drop(columns=columns_to_drop, inplace=True)

In [101]:
df

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# Data Cleaning:
---
1. Deleting redundant columns.
2. Renaming the columns.
3. Dropping duplicates.
4. Cleaning individual columns.
5. Remove the NaN values from the dataset
6. Check for some more Transformations

In [102]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [103]:
df.drop_duplicates(inplace=True)

In [104]:
df.shape

(18909, 6)

In [105]:
modified_names = df.columns.str.capitalize()

In [106]:
modified_names

Index(['Name', 'Online_order', 'Book_table', 'Rate', 'Dish_liked',
       'Approx_cost(for two people)'],
      dtype='str')

In [107]:
df.columns = modified_names

In [108]:
df.dropna(inplace=True)

In [109]:
df.reset_index(inplace=True)

In [110]:
df.drop(columns='index', inplace=True)

In [111]:
df['Rate'].tail()

8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, dtype: str

In [112]:
df['Rate'] = df['Rate'].str.replace(' ', '')
df['Rate'] = df['Rate'].str.replace('/', ' out of ')

In [113]:
df['Online_order'] = df['Online_order'].apply(lambda x: True if x == 'Yes' else False)
df['Book_table'] = df['Book_table'] == 'Yes'

In [114]:
df

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,True,True,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,True,False,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,True,False,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,False,False,3.7 out of 5,Masala Dosa,300
4,Grand Village,False,False,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,False,False,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,False,False,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,True,False,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,False,True,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,False,False,2.5 out of 5,"Biryani, Andhra Meal",800

In [115]:
df.to_csv('Zomato_Dataset_Cleaned.csv', index=False)